[project]
name = "mojo-learning"
version = "0.1.0"
description = "A learning environment for Mojo programming language"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.9"
jupyter = "*"
ipython = "*"
notebook = "*"
curl = "*"
wget = "*"
modular = "*"

[tasks]
start-jupyter = "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
hello-python = "echo 'print(\"Hello from Python!\")' > hello.py && python hello.py"
hello-mojo = "test -f hello.mojo || echo 'def main():\n    print(\"Hello from Mojo!\")' > hello.mojo && mojo hello.mojo"
check-mojo = "which mojo && mojo --version || echo 'Mojo not found - try: pixi shell'"
check-max = "which max && max --version || echo 'MAX not found - try: pixi shell'"
