[project]
name = "mojo-learning"
version = "0.1.0"
description = "A learning environment for Mojo programming language"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
max = "*"
python = ">=3.9"
jupyter = "*"
ipython = "*"
notebook = "*"

[tasks]
start-jupyter = "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
hello-mojo = "echo 'print(\"Hello from Mojo!\")' > hello.mojo && mojo hello.mojo"

[feature.dev.dependencies]
pytest = "*"
black = "*"
